name: Notify Microsoft Teams on PR Merge

on:
  pull_request:
    types: [opened,closed]  # Chỉ chạy khi PR được đóng (merged hoặc không)

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is merged
        id: check_merge
        run: |
          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            echo "merged=true" >> $GITHUB_ENV
          else
            echo "merged=false" >> $GITHUB_ENV
          fi

      - name: Convert merge time to Vietnam Time (UTC+07:00)
        if: env.merged == 'true'
        run: |
          export TZ=Asia/Ho_Chi_Minh
          MERGE_TIME=$(date -d "${{ github.event.pull_request.merged_at }}" +"%Y-%m-%dT%H:%M:%S%:z")
          echo "MERGE_TIME=$MERGE_TIME" >> $GITHUB_ENV

      - name: Send Notification to Microsoft Teams
        if: env.merged == 'true'
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "text": "[**Merge pull request #${{ github.event.pull_request.number }} from ${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}**](${{ github.event.pull_request.html_url }})\n
            **Branch**: ${{ github.event.pull_request.base.ref }}\n
            **Author**: ${{ github.event.pull_request.user.login }}\n
            **Time**: ${{ env.MERGE_TIME }}"
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
