name: Notify Teams
on: pull_request
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Teams
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "text": "**New Commit**: [Merge PR #4](https://your-github-enterprise.com/repo/pull/4)"
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
